TERMUX_PKG_HOMEPAGE=https://wiki.termux.com/wiki/Termux:API
TERMUX_PKG_DESCRIPTION="Termux API commands (install also the Termux:API app)"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.54.1
TERMUX_PKG_SRCURL=https://github.com/chengyehwang/termux-api-package/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ceaf204da045f2a606e9d7c968c57d84b469392173f11cf4ca5faa2f2214a518
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="bash, util-linux"
